awslabs/aws-mobile-appsync-sdk-ios

- AWSAppSyncClient/AppSyncMQTTClient.swift
**Issue-#9** *Crash on unsubscribing a Watcher*
Changes:
* added safe workflow for changing dictionary and array of watchers
> Possible crash-fix for issue 9

- README.md
Minor changes in the readme. Fixing broken links.
@rohandubal @jpeddicord Please merge.
> Fixing broken links in the Readme

- AWSAppSyncClient/AWSSQLLiteNormalizedCache.swift
*Issue fixed : the sqlLite database could be locked because the busytimout property on sqllite db connection is by default set to 0
When a lock occurs a crash occurs because there is no retry 
Set db.busytimout  to a positive value in order to retry when a lock occurs in  AWSSQLLiteNormalizedCache.swift
> fix sqllite lock issue

- AWSAppSync.podspec
- AWSAppSyncClient/AWSAppSyncClient.swift
- AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift
- AWSAppSyncClient/Info.plist
- AWSAppSyncTests/AWSAppSyncTests.swift
- CHANGELOG.md
- docs/index.md
Add support for AWS AppSync configuration through awsconfiguration.json in AWSAppSyncClient.
> Add support for AWS AppSync configuration through awsconfiguration.json in AWSAppSyncClient.

- AWSAppSyncClient/AWSAppSyncClient.swift
> Fix a bug in loading configuration from awsconfiguration.json

- .travis.yml
- AWSAppSync.podspec
- AWSAppSyncClient/AWSAppSyncAuthProvider.swift
- AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift
- AWSAppSyncClient/Info.plist
- AWSAppSyncTests/AuthProviderTests.swift
- CHANGELOG.md
> Changes for 2.6.20. Add UserPools Async Auth provider. Fix Travis Build.

- AWSAppSyncClient/MQTTSDK/AWSIoTMQTTClient.m
- CHANGELOG.md
- stage_sdk_release.sh
Script helps stage SDK release locally.
> Add SDK release staging utility script. Add CHANGELOG for 2.6.21

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Ask a standard standard set of questions to users opening issues on the repo.
> Add issue templates for feature requests and bug reports

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> Minor formatting change

- AWSAppSyncTests/AppSyncMQTTClientTests.swift
> Increase timeout for MQTT Client Test

- AWSAppSync.podspec
- AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift
- AWSAppSyncClient/Info.plist
- CHANGELOG.md
- Cartfile
- Podfile
Update `AWSCore` dependency from `2.6.x` to `2.7.x`
> Release SDK version 2.6.24

- AWSAppSync.podspec
- Podfile
N/A
Bump ReachabilitySwift to 4.3.0
> Bump ReachabilitySwift to 4.3.0

- AWSAppSyncClient.xcodeproj/project.pbxproj
- AWSAppSyncTests/AWSAppSyncAPIKeyAuthTests.swift
- AWSAppSyncTests/AWSAppSyncTests.swift
- AWSAppSyncTests/DefaultEventTestData.swift
- AWSAppSyncTests/SubscriptionStressTestHelper.swift
N/A
Fixed unstable subscription stress tests
> Fixed unstable subscription stress tests

- AWSAppSyncClient/AWSAppSyncSubscriptionMetadataCache.swift
- AWSAppSyncTests/AWSAppSyncAPIKeyAuthTests.swift
Fixing PR bad branch push from #102 
> Add test for sync behavior. Fix regression in subscription metadata cache.

- AWSAppSyncClient.xcodeproj/project.pbxproj
- AWSAppSyncClient/AppSyncSubscriptionWithSync.swift
- AWSAppSyncTests/AWSAppSyncAPIKeyAuthTests.swift
- AWSAppSyncTests/AWSAppSyncTests.swift
- AWSAppSyncTests/AppSyncClientTestConfiguration.swift
- AWSAppSyncTests/AppSyncClientTestConfigurationDefaults.swift
- AWSAppSyncTests/AppSyncClientTestHelper.swift
- AWSAppSyncTests/AuthProviderTests.swift
- README.md
N/A
Reorganize tests for easier editing & greater stability.
> Test refactoring

- AWSAppSyncClient/AWSAppSyncClient.swift
> Fix reachability check

- AWSAppSync.podspec
- Cartfile
- Podfile
> Bump SQLite.swift to 0.11.5

- AWSAppSyncIntegrationTests/AWSAppSyncCognitoAuthTests.swift
- AWSAppSyncIntegrationTests/AuthProviderTests.swift
> Add cachePolicy to integration tests that rely on bypassing cache

- AWSAppSyncClient/Internal/AppSyncMQTTClient.swift
- AWSAppSyncClient/MQTTSDK/AWSIoTMQTTClient.m
> propagate connection error status in case of error fetching credentials.

- AWSAppSync.podspec
- AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift
- AWSAppSyncClient/Info.plist
> Version bump

- AWSAppSyncTestCommon/AppSyncClientTestHelper.swift
Update error message print out of correct json file
> Fix integration test helper region mismatch for identity pool

- AWSAppSyncClient/AWSAppSyncCache.swift
- AWSAppSyncClient/AWSAppSyncClient.swift
> Fix Swift lint errors.

- .gitignore
- AWSAppSyncIntegrationTests/ConsoleResources/appsync-integrationtests-cloudformation.yaml
- AWSAppSyncTestCommon/AppSyncClientTestHelper.swift
- README.md
*Issue #, if available:* Current readme and cloud formation template is out of date.
*Description of changes:* Added instructions to include multi auth details in testing steps. Updated cloudformation template to create resources for multi auth.
Also added .DS_Store to gitignore
> Fixed testing doc and yaml used for testing

- README.md
> Update AppSync version in README

- AWSAppSyncIntegrationTests/AWSAppSyncCognitoAuthTests.swift
> Use unique NSURLSession background id for tests

- AWSAppSync.podspec
#297 
Update AWS Core dependency in Podspec.
> Updated AWSCore dependency in Podspec

- AWSAppSyncUnitTests/MutationQueueTests.swift
Fixed race condition waiting for operation queue to be emptied
> Fix race condition in testCancelAllMutations

- AWSAppSyncClient/Internal/AppSyncSubscriptionWithSync.swift
- CHANGELOG.md
> Remove force-unwrap

- AWSAppSyncClient/Internal/AWSAppSyncRetryHandler.swift
- AWSAppSyncUnitTests/AWSAppSyncRetryHandlerTests.swift
> Fix crash when retry handler attemptNumber is >= 57 (#339)

- AWSAppSync.podspec
- AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift
- AWSAppSyncClient/Internal/AppSyncSubscriptionWithSync.swift
- AWSAppSyncClient/Internal/AuthInterceptor/IAMAuthInterceptor.swift
- Cartfile
- Podfile
- Podfile.lock
- Pods/AWSAuthCore/README.md
- Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/CognitoIdentityProvider/AWSCognitoIdentityProviderModel.h
- Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/CognitoIdentityProvider/AWSCognitoIdentityProviderModel.m
- Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/CognitoIdentityProvider/AWSCognitoIdentityProviderResources.m
- Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/CognitoIdentityProvider/AWSCognitoIdentityProviderService.m
- Pods/AWSCognitoIdentityProvider/README.md
- Pods/AWSCore/AWSCore/Authentication/AWSSignature.h
- Pods/AWSCore/AWSCore/Service/AWSService.m
- Pods/AWSCore/README.md
- Pods/AWSMobileClient/AWSCognitoAuth/AWSCognitoAuth.m
- Pods/AWSMobileClient/README.md
- Pods/AWSS3/AWSS3/AWSS3PreSignedURL.m
- Pods/AWSS3/AWSS3/AWSS3Service.m
- Pods/AWSS3/AWSS3/AWSS3TransferUtility.m
- Pods/AWSS3/AWSS3/AWSS3TransferUtilityTasks.m
- Pods/AWSS3/README.md
- Pods/Manifest.lock
- Pods/Target Support Files/AWSAuthCore/AWSAuthCore-Info.plist
- Pods/Target Support Files/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider-Info.plist
- Pods/Target Support Files/AWSCore/AWSCore-Info.plist
- Pods/Target Support Files/AWSMobileClient/AWSMobileClient-Info.plist
- Pods/Target Support Files/AWSS3/AWSS3-Info.plist
this upgrade AWSCore to 2.13.0 and fixes some of the nullability changes that was introduced in 2.13.0
> Upgrade AWSCore to 2.13.0

- CHANGELOG.md
> Update changelog for 3.1.0

- AWSAppSyncClient/Internal/CachedMutationOperation.swift
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docs/_config.yml
> chore: Changed the repo's default branch to 'main'

- CHANGELOG.md
- Update changelog for release
> chore: Prep 3.1.6 release

- CHANGELOG.md
> chore: prep 3.1.8 release

- AWSAppSync.podspec
update podspec to match previous SDK update to 2.17.0
> fix: update podspec to match 2.17.0

- CHANGELOG.md
> chore: prep 3.1.9 release

- AWSAppSync.podspec
- Cartfile
- Podfile
- Podfile.lock
- Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/AWSCognitoIdentityProviderModel.m
- Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/AWSCognitoIdentityProviderService.m
- Pods/AWSCore/AWSCore/CognitoIdentity/AWSCognitoIdentityModel.m
- Pods/AWSCore/AWSCore/Networking/AWSNetworking.m
- Pods/AWSCore/AWSCore/STS/AWSSTSModel.m
- Pods/AWSCore/AWSCore/Service/AWSService.m
- Pods/AWSCore/AWSCore/TMCache/AWSTMDiskCache.m
- Pods/AWSCore/AWSCore/Utility/AWSModel.h
- Pods/AWSCore/AWSCore/Utility/AWSModel.m
- Pods/AWSMobileClient/AWSCognitoAuth/AWSCognitoAuth.m
- Pods/AWSS3/AWSS3/AWSS3PreSignedURL.m
- Pods/AWSS3/AWSS3/AWSS3Service.m
- Pods/Manifest.lock
- Pods/Target Support Files/AWSAuthCore/AWSAuthCore-Info.plist
- Pods/Target Support Files/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider-Info.plist
- Pods/Target Support Files/AWSCognitoIdentityProviderASF/AWSCognitoIdentityProviderASF-Info.plist
- Pods/Target Support Files/AWSCore/AWSCore-Info.plist
- Pods/Target Support Files/AWSMobileClient/AWSMobileClient-Info.plist
- Pods/Target Support Files/AWSS3/AWSS3-Info.plist
Updated dependencies after bumping the SDK version with the script added in https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/431
> chore: Update SDK dependencies

- AWSAppSync.podspec
- AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift
- AWSAppSyncClient/Info.plist
- CHANGELOG.md
- README.md
> Release SDK version 3.1.11

- README.md
> Update Readme.md to update documentation link

- AWSAppSyncIntegrationTests/ConsoleResources/appsync-integrationtests-cloudformation.yaml
> chore: add a parameter for the api key expiration

- AWSAppSync.podspec
- Cartfile
- Podfile
- Podfile.lock
- Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/AWSCognitoIdentityProviderService.m
- Pods/AWSCore/AWSCore/Service/AWSService.m
- Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.swift
- Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift
- Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileOptions.swift
- Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/Internal/AWSCognitoAuth+Extensions.h
- Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/Internal/AWSCognitoAuth+Extensions.m
- Pods/AWSMobileClient/AWSCognitoAuth/AWSCognitoAuth.h
- Pods/AWSMobileClient/AWSCognitoAuth/AWSCognitoAuth.m
- Pods/AWSS3/AWSS3/AWSS3PreSignedURL.m
- Pods/AWSS3/AWSS3/AWSS3Service.m
- Pods/Manifest.lock
- Pods/Target Support Files/AWSAuthCore/AWSAuthCore-Info.plist
- Pods/Target Support Files/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider-Info.plist
- Pods/Target Support Files/AWSCognitoIdentityProviderASF/AWSCognitoIdentityProviderASF-Info.plist
- Pods/Target Support Files/AWSCore/AWSCore-Info.plist
- Pods/Target Support Files/AWSMobileClient/AWSMobileClient-Info.plist
- Pods/Target Support Files/AWSS3/AWSS3-Info.plist
**Description of changes:**
Upgrade to SDK 2.22.0
> chore: Update dependencies

- AWSAppSyncClient/Internal/AppSyncSubscriptionWithSync.swift
- AWSAppSyncUnitTests/AppSyncSubscriptionWithSyncTests.swift
This unit test is inconsistent. So I think we have a couple options..
Option 1.  Just comment out the test, because there is clearly a race condition between an operation that is scheduled to start during instantiation and calling `cancel()`.  This is the approach implemented here:
https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/426
Option 2. Implemented in this PR -- Allow the operation to start, cancel it, and then assert the state to make sure we have canceled the operation.  This seems like a reasonable approach, but introduces some risk since we are changing isCancelled to an atomic (that being said, it is the right thing to do since it can be accessed by multiple threads.
Overall the code isn't set up to be testable, so I think this option strikes a good balance between …
> chore: fix testCancel() to make consistent

- AWSAppSync.podspec
- AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift
- AWSAppSyncClient/Info.plist
- CHANGELOG.md
- Podfile.lock
- Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/Connection/AppSyncConnection/AppSyncSubscriptionConnection+ErrorHandler.swift
- Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/Connection/AppSyncConnection/AppSyncSubscriptionConnection.swift
- Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider+StaleConnection.swift
- Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider+Websocket.swift
- Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider.swift
- Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/ConnectionProvider/ConnectionProviderFactory.swift
- Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/Support/AppSyncJSONHelper.swift
- Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/Support/CountdownTimer.swift
- Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/Support/SubscriptionConstants.swift
- Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/Websocket/Starscream/StarscreamAdapter.swift
- Pods/Manifest.lock
- Pods/Target Support Files/AppSyncRealTimeClient/AppSyncRealTimeClient-Info.plist
- README.md
> Palpatim.chore.prep release 3.1.15

- CHANGELOG.md
> chore: prep release 3.1.16

- README.md
> chore: Remove outdated carthage readme note

- .gitignore
- AWSAppSync.podspec
- Cartfile
- Podfile
- Podfile.lock
- Pods/AWSAuthCore/README.md
- Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/AWSCognitoIdentityProviderService.m
- Pods/AWSCognitoIdentityProvider/README.md
- Pods/AWSCognitoIdentityProviderASF/README.md
- Pods/AWSCore/AWSCore/Service/AWSService.m
- Pods/AWSCore/README.md
- Pods/AWSMobileClient/AWSCognitoAuth/AWSCognitoAuth.m
- Pods/AWSMobileClient/README.md
- Pods/AWSS3/AWSS3/AWSS3PreSignedURL.m
- Pods/AWSS3/AWSS3/AWSS3Service.m
- Pods/AWSS3/README.md
- Pods/Manifest.lock
- Pods/Target Support Files/AWSAuthCore/AWSAuthCore-Info.plist
- Pods/Target Support Files/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider-Info.plist
- Pods/Target Support Files/AWSCognitoIdentityProviderASF/AWSCognitoIdentityProviderASF-Info.plist
- Pods/Target Support Files/AWSCore/AWSCore-Info.plist
- Pods/Target Support Files/AWSMobileClient/AWSMobileClient-Info.plist
- Pods/Target Support Files/AWSS3/AWSS3-Info.plist
- Pods/Target Support Files/AppSyncRealTimeClient/AppSyncRealTimeClient-Info.plist
- build-support/update_sdk_deps.sh
> feat: Update dependencies to support installation via Swift Package Manager

- CHANGELOG.md
- README.md
> chore: Add support docs for Swift Package Manager

- CHANGELOG.md
> Update CHANGELOG.md 3.2.1

- AWSAppSync.podspec
- Cartfile
- Package.resolved
- Package.swift
- Podfile
- Podfile.lock
- Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/AWSCognitoIdentityProviderService.m
- Pods/AWSCore/AWSCore/Service/AWSService.m
- Pods/AWSMobileClient/AWSCognitoAuth/AWSCognitoAuth.m
- Pods/AWSS3/AWSS3/AWSS3.h
- Pods/AWSS3/AWSS3/AWSS3PreSignedURL.m
- Pods/AWSS3/AWSS3/AWSS3Service.m
- Pods/AWSS3/AWSS3/AWSS3TransferUtility+EnumerateBlocks.h
- Pods/AWSS3/AWSS3/AWSS3TransferUtility+EnumerateBlocks.m
- Pods/AWSS3/AWSS3/AWSS3TransferUtility.h
- Pods/AWSS3/AWSS3/AWSS3TransferUtility.m
- Pods/AWSS3/AWSS3/AWSS3TransferUtilityBlocks.h
- Pods/AWSS3/AWSS3/AWSS3TransferUtilityBlocks.m
- Pods/Manifest.lock
- Pods/Pods.xcodeproj/project.pbxproj
- Pods/Target Support Files/AWSAuthCore/AWSAuthCore-Info.plist
- Pods/Target Support Files/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider-Info.plist
- Pods/Target Support Files/AWSCognitoIdentityProviderASF/AWSCognitoIdentityProviderASF-Info.plist
- Pods/Target Support Files/AWSCore/AWSCore-Info.plist
- Pods/Target Support Files/AWSMobileClient/AWSMobileClient-Info.plist
- Pods/Target Support Files/AWSS3/AWSS3-Info.plist
- Pods/Target Support Files/AWSS3/AWSS3-umbrella.h
- Compared to https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/472
- Ran integ tests and unit tests
> Update to SDK 2.26.0

- CHANGELOG.md
> Update CHANGELOG.md for 3.4.1 release

- build-support/carthage-build.sh
Update Carthage build script to support Xcode 13
> chore: update carthage build script

- CHANGELOG.md
> Update CHANGELOG.md 3.5.0

- build-support/build-xcframeworks.sh
Reduce release build log https://app.travis-ci.com/github/awslabs/aws-mobile-appsync-sdk-ios/builds/247030724#L13573
> chore: reduce release build logging

- CHANGELOG.md
> Update CHANGELOG.md 3.6.0

- AWSAppSyncClient/AWSAppSyncClientConfiguration.swift
> chore: Update url cache default to no cache

- AWSAppSync.podspec
- AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift
- AWSAppSyncClient/Info.plist
- README.md
*Issue #, if available:* None
*Description of changes:* Release SDK version 3.6.2
> Release SDK version 3.6.2

- AWSAppSyncIntegrationTests/AWSAppSyncCognitoAuthTests.swift
- AWSAppSyncIntegrationTests/AWSAppSyncLambdaAuthTests.swift
- AWSAppSyncIntegrationTests/Helpers/SubscriptionStressTestHelper.swift
- AWSAppSyncIntegrationTests/SubscriptionTests.swift
- AWSAppSyncTestApp/ViewController.swift
- AWSAppSyncUnitTests/AWSAppSyncRetryHandlerTests.swift
- AWSAppSyncUnitTests/AppSyncApolloCustomizationTests.swift
- AWSAppSyncUnitTests/MutationOptimisticUpdateTests.swift
- AWSAppSyncUnitTests/MutationQueueTests.swift
- AWSAppSyncUnitTests/ReachabilityChangeNotifierTests.swift
- ApolloTests/TestCacheProvider.swift
*Issue #, if available:* None
*Description of changes:* Fix build warnings in test schemes
> chore: fix test build warnings

- .swiftlint.yml
- AWSAppSyncClient.xcodeproj/project.pbxproj
- AWSAppSyncClient/AWSAppSyncClient.swift
- AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift
- AWSAppSyncClient/AWSAppSyncReachability.swift
- AWSAppSyncClient/Internal/AWSAppSyncRetryHandler.swift
- AWSAppSyncClient/Internal/AppSyncSubscriptionWithSync.swift
*Issue #, if available:* None
*Description of changes:* This PR introduces changes to fix Swiftlint violations in the project.
> chore: fix swiftlint violations

- AWSAppSyncClient/AWSAppSyncClient.swift
- AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift
- AWSAppSyncClient/Apollo/Sources/Apollo/ApolloClient.swift
- AWSAppSyncClient/Apollo/Sources/Apollo/ApolloStore.swift
- AWSAppSyncClient/Apollo/Sources/Apollo/GraphQLOperation.swift
- AWSAppSyncClient/Apollo/Sources/Apollo/GraphQLResultAccumulator.swift
- AWSAppSyncClient/Internal/AppSyncSubscriptionWithSync.swift
- AWSAppSyncClient/NetworkReachability.swift
*Issue #, if available:* None
*Description of changes:* Fix deprecation build warnings
> chore: fix deprecation build warnings

- AWSAppSyncClient/AWSAppSyncClient.swift
- AWSAppSyncClient/AWSAppSyncClientConflictResolutionExtensions.swift
- AWSAppSyncClient/Internal/AppSyncSubscriptionWithSync.swift
I found properties that no need to be optional type.
> Make properties non-optional

- AWSAppSync.podspec
- Cartfile
- Package.resolved
- Package.swift
- Podfile
- Podfile.lock
**Description of changes:**
Updating the SDK dependency version to `2.32.0`
> chore: Updating SDK dependency version to 2.32.0

- README.md
Adds notice to readme about maintenance mode.
> chore: update readme with notice about maintenance mode

- AWSAppSyncClient/Internal/SubscriptionFactory/IAMBasedConnectionPool.swift
> chore: fix swiftlint spacing error

- AWSAppSync.podspec
- AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift
- AWSAppSyncClient/Info.plist
- README.md
> chore: Release SDK version 3.6.3

- AWSAppSync.podspec
- AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift
- AWSAppSyncClient/Info.plist
- README.md
This PR releases a new version of the AppSync SDK
> chore: Release SDK version 3.6.4

- CHANGELOG.md
- update change log for `3.6.5`
> chore: update changelog for 3.6.5

- AWSAppSync.podspec
- AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift
- AWSAppSyncClient/Info.plist
- README.md
> release 3.6.5 [skip ci]

- AWSAppSync.podspec
- AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift
- AWSAppSyncClient/Info.plist
- CHANGELOG.md
- README.md
- update changelog
- bump version to 3.7.0
> chore: release 3.7.0

- AWSAppSync.podspec
- AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift
- AWSAppSyncClient/Info.plist
- CHANGELOG.md
- README.md
> chore: Release SDK version 3.7.1
