AWSAppSyncClient/MQTTSDK/SocketRocket/AWSSRWebSocket.m
AppSync's custom socket rocket clashes with the real one when used together, generating duplicated symbols.
Description of changes:
Prefixed internal socket rocket classes with 'AWS'
(Sorry, I closed the other one by mistake when moving some branches around)
=> Renamed private AWSSRWebSocket classes in order to avoid duplicated symbols when the client project relies on the real SocketRocket

AWSAppSyncClient/AWSAppSyncClient.swift
Calling the AWSAppSyncClientConfiguration connectionStateChangeHandler on network availability changes and using .Online when the endpoint is reachable.
=> Calling the AWSAppSyncClientConfiguration connectionStateChangeHandler

AWSAppSyncClient.xcodeproj/project.pbxproj, AWSAppSyncClient/AWSAppSyncClient.swift, AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift, AWSAppSyncClient/AWSAppSyncSubscriptionWatcher.swift, AWSAppSyncClient/AWSNetworkTransport.swift, AWSAppSyncClient/AWSOfflineMutationStore.swift
Issue #38 
The purpose of this PR is to expose the NetworkTransport class that is used by the App Sync SDK so it is possible to create a Mock Network Transport object to control what responses from the server look like in our Functional UI tests.
* Creating a protocol outlining the requirements for a NetworkTransport class
* Modifying internal dependecies on the concrete AWSAppSyncHTTPNetworkTransport class, so they are only depedent on the protocol
* Exposing a new configuration initializer for app sync where the app can create their own network transport class. This includes a small refactor to the configuration class.
=> AWSNetworkTransport modifications to enable the ability to mock server

docs/index.md
This line seems to be here by mistake.
N/A
Remove "Save the We will use this folder for storing our GraphQL related files."
=> Fixing customer reported documentation issue

AWSAppSyncClient.xcodeproj/project.pbxproj, AWSAppSyncClient/AWSAppSyncAuthProvider.swift, AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift, AWSAppSyncTests/AuthProviderTests.swift
This is an updated to an earlier PR that provides a backward compatible way for fetching auth tokens in a synchronous or asynchronous way.
When using a CognitoUserPoolsAuthProvider or AWSOIDCAuthProvider, a client can create an auth provides that alternatively uses a callback:
```swift
class MyOIDCAuthProvider: AWSOIDCAuthProviderAsync {   
func getLatestAuthToken(_ callback: @escaping (String) -> Void) {
functionThatMakesNetworkCall(){ token in 
callback(token)
}
}
}
```
Using AWSCognitoUserPoolsAuthProvider instead:
```swift
class CognitoUserPoolsAuthProviderAsync: AWSCognitoUserPoolsAuthProvider, AWSOIDCAuthProviderAsync {
func getLatestAuthToken(_ callback: @escaping (String) -> Void) {
functionThatMakesNetworkCall(){ token in 
callback(token)
}
}
}
```
See …
=> Allow Auth credentials to be fetched via callback, backwards compatible

AWSAppSyncClient/AWSAppSyncClient.swift, AWSAppSyncClient/AWSOfflineMutationStore.swift, AWSAppSyncTests/AWSAppSyncTests.swift
Partially related to issue #79.
Problem:
Class `AWSAppSyncClient` sets up 2 retain cycles in its initializer which prevent deallocation.
Solution:
1. Cycle in `MutationExecutor` broken by using a `weak` reference
2. Cycle in `AWSAppSyncClient` itself broken by not adding `self` to `networkStatusWatchers` array but instead just invoking method on self directly later in code.
Verification:
A new unit test confirming `AWSAppSyncClient` gets deallocated.
=> Resolved retain cycles in AWSAppSyncClient

AWSAppSyncClient.xcodeproj/project.pbxproj, AWSAppSyncClient.xcodeproj/xcuserdata/rohandub.xcuserdatad/xcschemes/xcschememanagement.plist, AWSAppSyncClient/AWSAppSyncClient.swift, AWSAppSyncClient/AWSAppSyncSubscriptionWatcher.swift, AWSAppSyncClient/AppSyncMQTTClient.swift, AWSAppSyncClient/MQTTSDK/AWSIoTMQTTClient.h, AWSAppSyncClient/MQTTSDK/AWSIoTMQTTClient.m, AWSAppSyncTests/AppSyncMQTTClientTests.swift, CHANGELOG.md
Fixes issues reported in #82 
Avoid retain cycles and memory leaks in MQTT SDK. 
Validated changes by running all functional tests and also verified through Xcode's memory graph using a sample app.
=> Bug fixes for avoiding retain cycles and memory leaks.

Cartfile
N/A
Previously, this resolved to the "v3" tag. This change will ensure that both Carthage and CocoaPods versions are built with the same ReachabilitySwift version.
=> Update ReachabilitySwift to 4.3.0 in Cartfile

AWSAppSyncClient/AppSyncSubscriptionWithSync.swift, AWSAppSyncTests/AWSAppSyncAPIKeyAuthTests.swift
Rename sync parameter to `baseRefreshIntervalInSeconds`
=> Update SyncConfiguration parameter for sync method.

AWSAppSyncClient/AWSAppSyncRetryHandler.swift
Replace `random` with Swift 4.2 version
=> Replace `random` with Swift 4.2 version

.swiftlint.yml, AWSAppSyncClient.xcodeproj/project.pbxproj, AWSAppSyncClient/AWSAppSyncAuthProvider.swift, AWSAppSyncClient/AWSAppSyncClient.swift, AWSAppSyncClient/AWSAppSyncClientConflictResolutionExtensions.swift, AWSAppSyncClient/AWSAppSyncClientS3ObjectsExtensions.swift, AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift, AWSAppSyncClient/AWSAppSyncRetryHandler.swift, AWSAppSyncClient/AWSAppSyncSubscriptionWatcher.swift, AWSAppSyncClient/AWSOfflineMutationStore.swift, AWSAppSyncClient/AWSS3ObjectProtocol.swift, AWSAppSyncClient/AWSSQLLiteNormalizedCache.swift, AWSAppSyncClient/Apollo/Sources/Apollo/ApolloStore.swift, AWSAppSyncClient/AppSyncMQTTClient.swift, AWSAppSyncClient/AppSyncSubscriptionWithSync.swift, AWSAppSyncClient/Internal/AppSyncLogWrapper.swift
- add simple SwiftLint configuration
- fix some linter warnings and errors
=> Add simple SwiftLint configuration

.travis.yml, CHANGELOG.md, README.md
N/A
Updated README with better documentation for Carthage. Updated Travis-CI config to use Xcode 10.1 image so Carthage binaries will be built with Swift 4.2.1.
=> Build using Xcode 10.1 in Travis

AWSAppSyncClient.xcodeproj/project.pbxproj
NA
Currently for some reason valid architectures are only "armv7 arm64 armv7s", but for example the latest Xcode 10 supports `arm64e`.  I think that valid architectures should be default that Xcode sets if there're no any specific reasons.
=> Fix valid architectures

AWSAppSyncClient/Apollo/Sources/Apollo/Collections.swift
https://github.com/apollographql/apollo-ios/pull/427
Fixes #163
Merge https://github.com/apollographql/apollo-ios/pull/427 to forked copy of Apollo/Collections.swift, to fix incompatibility with EnumeratedIterator type.
=> Merge Apollo PR: "Update for compatibility with Swift5"

AWSAppSyncClient.xcodeproj/project.pbxproj, AWSAppSyncClient/AWSAppSyncClientConfiguration.swift, AWSAppSyncClient/Internal/AWSSQLiteNormalizedCache.swift, AWSAppSyncUnitTests/MutationOptimisticUpdateTests.swift, CHANGELOG.md
#92 
Prepopulated both AWSSQLiteNormalizedCache and InMemoryNormalizedCache with an empty QUERY_ROOT record to allow optimistic updates of empty caches. Works around an Apollo behavior that is arguably a bug, but that I'm reluctant to change for fear of unintended side effects in the rest of the handling. See discussion on #92.
=> Prepopulate records table with empty QUERY_ROOT (#92)

AWSAppSyncClient.xcodeproj/project.pbxproj, AWSAppSyncClient/Apollo/Sources/Apollo/ApolloClient.swift, AWSAppSyncClient/Apollo/Sources/Apollo/GraphQLResult.swift, ApolloTests/FetchQueryTests.swift, ApolloTests/FetchQueryTestsComplex.swift, ApolloTests/FetchQueryTestsSimple.swift, CHANGELOG.md, StarWarsAPI/API.swift
Fixed regression from #177 (cache-misses resulting from prepopulating caches with an empty QUERY_ROOT). Added tests to verify query behavior against different cache-miss conditions. This work also fiixes #90.
- #90
- #181 
=> Resolve cache-miss behavior for AppSync-modified Apollo client

AWSAppSyncClient.xcodeproj/project.pbxproj, AWSAppSyncClient/Internal/AWSSQLiteNormalizedCache.swift, AWSAppSyncUnitTests/CacheKeyTests.swift, AWSAppSyncUnitTests/Helpers/UnitTestHelpers.swift, AWSAppSyncUnitTests/MutationOptimisticUpdateTests.swift, AWSAppSyncUnitTests/MutationQueueTests.swift, ApolloTests/CachePersistenceTests.swift, ApolloTests/TestCacheProvider.swift, CHANGELOG.md, StarWarsAPI/API.swift, StarWarsAPI/HumanFriendsFilteredById.graphql, StarWarsAPI/StarWarsAPI.h, StarWarsAPI/schema.json
- Fix optimistic update tests to wait for optimistic update to complete before
fetching
- Added unit test helper for some utility functions
- Ported Apollo's CachePersistenceTests from their HEAD
- Added new field, 'friendsFilteredById', to allow easier testing of arguments
with arbitrary string constructions
- Added persistence tests for arguments with dots
- #110 
- #165 
=> Fix cacheKeyForObject handling for keys with dots (#110, #165)

AWSAppSync.podspec, AWSAppSyncClient.xcodeproj/project.pbxproj, AWSAppSyncClient/AWSAppSyncClient.swift, AWSAppSyncClient/AWSAppSyncClientConflictResolutionExtensions.swift, AWSAppSyncClient/AWSAppSyncClientLogFormatter.swift, AWSAppSyncClient/AWSAppSyncClientS3ObjectsExtensions.swift, AWSAppSyncClient/Apollo/Sources/Apollo/Record.swift, AWSAppSyncClient/Internal/AWSAppSyncSubscriptionMetadataCache.swift, AWSAppSyncClient/Internal/AWSMutationCache.swift, AWSAppSyncClient/Internal/AWSOfflineMutation.swift, AWSAppSyncClient/Internal/AWSPerformMutationOperation.swift, AWSAppSyncClient/Internal/AWSPerformMutationQueue.swift, AWSAppSyncClient/Internal/AWSPerformOfflineMutationOperation.swift, AWSAppSyncClient/Internal/AWSSQLiteNormalizedCache.swift, AWSAppSyncClient/Internal/AppSyncLogHelper.h, AWSAppSyncClient/Internal/AppSyncLogHelper.m, AWSAppSyncClient/Internal/AppSyncLogWrapper.swift, CHANGELOG.md
- Added logging helpers, added logging around mutation queue actions
- AppSyncLog's `message` argument is now an autoclosure
- Removed unused DispatchGroup from send operation
- Removed unused context arg to send
Fixes pending release: #190
=> Fixed incorrect AWSCore dependency version in podspec

AWSAppSyncClient/Internal/AWSPerformMutationOperation.swift, AWSAppSyncUnitTests/MutationQueueTests.swift, CHANGELOG.md
Fix a bug in AWSPerformMutationOperation.cancle, so that a mutation can be deleted from the persistent database when it's canceled ([Issue #187](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/187))
=> delete an  offline mutation from cache when it's canceled

AWSAppSyncIntegrationTests/ConsoleResources/appsync-integrationtests-cloudformation.yaml
The BucketName and BucketRegion are only available if choosing IAM as the auth type.
=> Update integration test cloudformation

AWSAppSyncClient/Internal/SessionMutationOperation.swift, AWSAppSyncUnitTests/MutationQueueTests.swift, CHANGELOG.md
#187 
- The `cancel` logic was missing a callback to the `operationCompletionHandler` which is responsible for deleting the mutation from the queue. Added a callback and ensured developer callback is not invoked in that case.
Integration and unit tests pass locally.
=> Fix issue #187. Remove mutation from persistent store when cancelled.

AWSAppSyncClient.xcodeproj/project.pbxproj, AWSAppSyncClient/AWSAppSyncClient.swift, AWSAppSyncClient/Internal/NetworkReachability.swift, AWSAppSyncClient/Internal/NetworkReachabilityNotifier.swift, AWSAppSyncClient/NetworkReachability.swift
Merging this PR will make
* **initializer** `AWSAppSyncClient.init(appSyncConfig:reachabilityFactory:)` public, and
* **protocols** `NetworkReachabilityProvidingFactory` and `NetworkReachabilityProviding` public
which are all `internal` to the framework for now.
*Rationale behind changes:*
By allowing framework users access to above API it will be possible to
* **mock** the reachability service properly for integration tests
* **substitute** the reachability service with a private solution if already present in a project
*Test results*
The proposed changes have no effect on unit or integration tests. All tests succeed w/ changes
applied.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
=> Make network reachability provider mockable

AWSAppSyncClient.xcodeproj/project.pbxproj, AWSAppSyncClient/AWSAppSyncSubscriptionWatcher.swift, AWSAppSyncClient/Internal/AppSyncMQTTClient.swift, AWSAppSyncClient/MQTTSDK/AWSIoTMQTTClient.m, AWSAppSyncIntegrationTests/AppSyncMQTTClientTests.swift, CHANGELOG.md
- Better handling of user initiated `cancel`
- Better handling of MQTT issued error
- Previously if the `SubscriptionWatcher` received an error status, it was responsible to invoke clean up for `AppSyncMQTTClient` by calling `cancel`
-  New behavior does automatic clean up in `AppSyncMQTTClient` if a connection error is encountered
- New tests to verify separation of concern and above mentioned behavior
=> Improvements for subscription cancelleation and disconnects.

AWSAppSyncClient.xcodeproj/project.pbxproj, AWSAppSyncClient/AWSAppSyncSubscriptionWatcher.swift, AWSAppSyncIntegrationTests/SubscriptionTests.swift, AWSAppSyncUnitTests/SubscriptionCancelAndRestartTests.swift, CHANGELOG.md
#249 
- Signal the semaphore from `cancel` method since we do not want to block any other subscriptions
- Added unit test which validates the behavior
- Added functional test which validates the behavior with actual subscription requests
=> Fix a bug which blocks subscription from starting after being cancelled.

AWSAppSyncClient.xcodeproj/xcshareddata/xcschemes/AWSAppSync.xcscheme, AWSAppSyncClient/Internal/AppSyncMQTTClient.swift
Tests pass locally.
From this change, the team will be responsible for running the integration tests locally, using the us-east-2 credentials, prior to a release.
=> Skipping integ tests by default b/c of TravisCI instability

AWSAppSyncClient.xcodeproj/project.pbxproj, AWSAppSyncClient/AWSAppSyncSubscriptionWatcher.swift, AWSAppSyncUnitTests/SubscriptionMiscTests.swift
*Issue*
- A customer reported that they are seeing a crash when accessing the dictionary in `SubscriptionsOrderHelper` when `4` subscription calls are made in quick succession
- Adding a delay of `0.1s` resolved the issue for them, but it is a temporary workaround
- The issue cannot be reproduced via functional tests
- The issue happens randomly in app when delay is not added, can be reproduced but not consistently
- Improve the logic of how `SubscriptionsOrderHelper` vends unique IDs to watchers
- All existing tests pass
- There were some unused methods in `SubscriptionsOrderHelper` which are now deleted
=> Update subscriptions order helper logic.

AWSAppSyncClient.xcodeproj/project.pbxproj, AWSAppSyncClient/Internal/AppSyncSubscriptionWithSync.swift, AWSAppSyncUnitTests/AppSyncSubscriptionWithSyncTests.swift, CHANGELOG.md
Delta sync was using wrong hash to store the data in the local cache. This caused
delta sync to fail intermittently.
*Issue #:* 
#232 
*Description of changes:* 
Hash calculation used in delta calculation was wrong and was producing different results on the same input. This was caused due to the unordered representation of swift Dictionary object which we used for creating hash. This PR addresses this issue by sorting the dictionary content and then using it for hash calculation.
=> Fix delta sync bug

AWSAppSyncClient/MQTTSDK/AWSIoTMQTTClient.h, AWSAppSyncClient/MQTTSDK/AWSIoTMQTTClient.m
#273
Removes unused reconnection handling from the AppSync fork of AWSIoTMQTTClient
=> Remove unused reconnection handling from AWSIoTMQTTClient

AWSAppSyncClient/AWSAppSyncSubscriptionWatcher.swift
*Issue #, if available:* #258, #216 
*Description of changes:* Refactored the verbose logging message in the subscription watcher so that it will output the minimum between `data.count` and `128` bytes. This should prevent any out of bounds exception that could be caused by `Data.prefix(upTo:...)`
If this isn't the desired fix, please provide any direction and I can adjust as needed.
=> use minimum of the number of bytes or 128

AWSAppSyncClient/Internal/AppSyncSubscriptionWithSync.swift, AWSAppSyncIntegrationTests/AWSAppSyncMultiAuthClientsTests.swift, AWSAppSyncIntegrationTests/SubscriptionTests.swift, AWSAppSyncUnitTests/AppSyncSubscriptionWithSyncTests.swift
*Issue #342:*
Takes a `weak self` reference inside of the initial sync operation and dispatch timer for sync.
The integration test  `testDeltaSyncMetadataClear` had to be updated to take a strong reference of the `Cancellable` objects.
The integration test `testStartStopStartSubscriptions` also had to be updated, although this appeared to be failing previous to the changes provided here.
=> Fix strong retain cycles

AWSAppSyncClient/Internal/AppSyncSubscriptionWithSync.swift, AWSAppSyncUnitTests/AppSyncSubscriptionWithSyncTests.swift
*Issue #342, if available:*
calling cancel and holding strong retain cycle will not actually cancel as there are still operations that might exist on the internal operation queue.
=> Fix cancel to ensure events do not continue firing

AWSAppSync.podspec, Podfile, Podfile.lock, Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider.swift, Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/Interceptor/RealtimeGatewayURLInterceptor.swift, Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/Websocket/Starscream/StarscreamAdapter.swift, Pods/Manifest.lock, Pods/Target Support Files/AppSyncRealTimeClient/AppSyncRealTimeClient-Info.plist
Looks like 1.0.2 removed interceptors while current version takes ~1.0.0 which will pulls in 1.0.2 and has some classes missing like `RealtimeGatewayURLInterceptor`. I published `1.1.0` and need to bump the version of the consumers.
=> Use AppSyncRealTimeClient 1.1.0

AWSAppSync.podspec, Cartfile, Podfile, Podfile.lock, Pods/Manifest.lock, Pods/Target Support Files/AppSyncRealTimeClient/AppSyncRealTimeClient-Info.plist, README.md
**Update AppSyncRealTimeClient Dependency to ~> 1.1**
This is updated in both the cartfile and the podspec/podfile to take all minor versions from 1.1 up to and not including 2.0 of AppSyncRealTimeClient
**cartfile fix**
The Cartfile located at the root of the AppSyncClient repository is used when users run `carthage update` to determine which additional dependencies are needed. The reason for this is because AppSyncClient is managed by Cocoapods via Podfile. If AppSyncClient doesn't have a Cartfile, then the Carthage users in their projects containing a cartfile with `github "awslabs/aws-mobile-appsync-sdk-ios"` will just pull in AppSync source and build the AppSyncClient.framework and nothing else.
**Remove daltoniam/starscream for aws-amplify/aws-appsync-realtime-client-ios**
Since …
=> AppSyncRealTimeClient ~> 1.1 + Cartfile fix

README.md
`.travis.yml` runs with `osx_image: xcode11` so readme should reflect that
=> Update readme for carthage xcode 11

AWSAppSyncClient/AWSAppSyncCache.swift
It makes failing building for the following error: 
`Colon Violation: Colons should be next to the identifier when specifying a type and next to the key in dictionary literals. (colon)`
=> Fix SwiftLint error

CHANGELOG.md, Podfile.lock, Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider.swift, Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/ConnectionProvider/ConnectionProviderFactory.swift, Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/Websocket/Starscream/StarscreamAdapter.swift, Pods/Manifest.lock, Pods/Pods.xcodeproj/project.pbxproj, Pods/Target Support Files/AppSyncRealTimeClient/AppSyncRealTimeClient-Info.plist
https://github.com/aws-amplify/aws-appsync-realtime-client-ios/releases/tag/1.1.6
The pod upgrade introduces:
Socket Disconnect when no remaining subscriptions.
=> Use AppSyncRealTimeClient 1.1.6

.travis.yml, CHANGELOG.md, README.md
=> chore: Update TravisCI image and CocoaPods version

AWSAppSyncClient.xcodeproj/project.pbxproj, AWSAppSyncClient/AWSAppSyncSubscriptionWatcher.swift, AWSAppSyncUnitTests/JSONValueSerializationTests.swift
[Issue 401](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/401)
See Issue for details
=> Fix bug in subscription where data is not translated correctly to a format valid for JSONSerialization

CHANGELOG.md
Missed the release version in changelog before triggering the AppSync release of 3.1.6, so unfortunately this commit comes after a tagged commit with 3.1.6
=> chore: update changelog released 3.1.6 version

build-support/carthage-build.sh
There was an error during release of 3.1.7 that can be reproduced locally:
```
$ bash ./build-support/carthage-build.sh archive AWSAppSync
*** xcodebuild output can be found in /var/folders/wl/yhpbkfx93g38l3k0ts5f92_1kgt2sf/T/carthage-xcodebuild.54QdZf.log
Failed to read file or folder at /Users/[USER]/awslabs/aws-mobile-appsync-sdk-ios/Cartfile.resolved: Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile.resolved” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/[USER]/awslabs/aws-mobile-appsync-sdk-ios/Cartfile.resolved, NSUnderlyingError=0x7fb2a4524cb0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```
It looked like the carthage workaround script has hardcoded `build`, and …
=> fix: carthage script defaults to build only

build-support/update_sdk_deps.sh
This PR adds an SDK version update script. I tested by running the script, and following the instructions. Resulting PR from the update: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/432
=> chore: Add update_sdk_deps.sh build-support script

README.md
Due to the indentation in the codegen section, it was rendering as a block-quote.
The leading indentation has been stripped. The wording of the section has been simplified for clarify.
=> fix: codegen section was rendered as blockquote

AWSAppSyncClient.xcodeproj/project.pbxproj, AWSAppSyncClient/AWSAppSyncAuthProvider.swift, AWSAppSyncClient/AWSAppSyncAuthType.swift, AWSAppSyncClient/AWSAppSyncClientConfiguration.swift, AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift, AWSAppSyncClient/Internal/AuthInterceptor/LambdaAuthInterceptor.swift, AWSAppSyncClient/Internal/SubscriptionFactory/ConnectionPool/BasicSubscriptionConnectionFactory.swift, AWSAppSyncClient/Internal/SubscriptionFactory/LambdaBasedConnectionPool.swift, AWSAppSyncIntegrationTests/AWSAppSyncLambdaAuthTests.swift, AWSAppSyncIntegrationTests/ConsoleResources/appsync-lambda-authorizer.js, AWSAppSyncTestCommon/AppSyncClientTestConfiguration.swift, AWSAppSyncTestCommon/AppSyncClientTestConfigurationDefaults.swift, AWSAppSyncTestCommon/AppSyncClientTestHelper.swift, AWSAppSyncTestCommon/MockAuthProviders.swift, AWSAppSyncUnitTests/AWSAppSyncAuthTypeTests.swift, AWSAppSyncUnitTests/AWSAppSyncClientConfigurationTests.swift, AWSAppSyncUnitTests/Subscription/Connection/ConnectionPool/LambdaBasedConnectionPoolTests.swift, AWSAppSyncUnitTests/Subscription/Connection/ConnectionPool/SubscriptionConnectionFactoryTests.swift, README.md
This PR introduces the changes to support for AWS Lambda authorizer.
Customers will be able to use the new `AWS_LAMBDA` authorization type by providing an instance of a type conforming to the `AWSLambdaAuthProvider` protocol, similarly to as they currently do for OIDC.
Example of dx:
```swift
struct MyAuthProvider: AWSLambdaAuthProvider {
func getLatestAuthToken() -> String {
"custom-lambda-token"
}
}
``
let authProvider = MyAuthProvider()
let serviceConfig = try AWSAppSyncServiceConfig()
let config = try AWSAppSyncClientConfiguration(
appSyncServiceConfig: serviceConfig,
awsLambdaAuthProvider: authProvider)
let appSyncClient = try AWSAppSyncClient(appSyncConfig: config)
```
**References**
Amplify iOS PR: https://github.com/aws-amplify/amplify-ios/pull/1334 …
=> feat: AWS Lambda authorizer support

AWSAppSyncClient/Internal/AuthInterceptor/LambdaAuthInterceptor.swift, AWSAppSyncIntegrationTests/AWSAppSyncLambdaAuthTests.swift, AWSAppSyncTestCommon/AppSyncClientTestHelper.swift, AWSAppSyncTestCommon/MockAuthProviders.swift
Fix `LambdaAuthInterceptor` to call either the sync or async provider (AWSLambdaAuthProviderAsync) to retrieve the authorization token.
=> fix: lambda async auth provider

ApolloTests/ReadWriteFromStoreTests.swift, ApolloTests/WatchQueryTests.swift, ApolloTests/XCTestCase+Promise.swift
The tests are not compiling with Xcode13. This replaces the 'await' method with 'awaitWith' method to avoid using the 'await' keyword
=> fix: Update tests to avoid 'await' keyword

AWSAppSyncClient.xcodeproj/project.pbxproj, AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift, AWSAppSyncUnitTests/AWSAppSyncHTTPNetworkTransportTests.swift
https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/487
`activeTimers` is of type `[String: DispatchSourceTimer]` so accessing this does not appear to be thread safe in the code. `sendGraphQLRequest` under certain conditions will retry like when service returns 5xx (or other retry scenarios). It will create a new timer, set it on `activeTimers`, while other timers that were created already may fire and remove it's timer from `activeTimers`. A race condition could happen if T1 calls sendGraphQLRequest due to a previous timer firing, fails the request, completes on T2 and retry logic decides to create another timer which accesses `activeTimers`. T1 continues to the next line from `sendGraphQLRequest` and removes a timer, which …
=> fix: remove race condition on activeTimer access in AWSAppSyncHTTPNetworkTransport

build-support/build-xcframeworks.sh
`before_deploy` Travis-CI step gets called once for each `deploy_provider` so to prevent build failures (and speed up the build process) when building for cocoapods, this PR introduces a change to skip the XCFramework build if the destination folder already exists.
=> chore: skip build xcframework when build for cocoapods

AWSAppSyncClient/AWSAppSyncCache.swift, AWSAppSyncClient/Internal/SQLiteSerialization.swift
None.
We use a number of custom scalars with AWS AppSync in our codebase, which are successfully parsed from the AppSync service, and get stored within the SQLite cache, but fail to be deserialised and thus cause cache reads involving these types to completely fail. This has primarily meant that we are unable to cache these calls at all, relying on live data for calls relying on our custom scalar types.
This is exactly the same as [an issue raised on the Apollo library in 2018](https://github.com/apollographql/apollo-ios/issues/329), and was resolved by returning the `fieldJSONValue` from the `SQLiteSerialization.deserialize(fieldJSONValue:)`, which correctly returns the custom scalar value as-is ([in this …
=> fix: deserialization of custom scalars

AWSAppSyncClient/AWSAppSyncClientConfiguration.swift, AWSAppSyncClient/Apollo/Sources/Apollo/InMemoryNormalizedCache.swift, AWSAppSyncClient/Internal/AWSSQLiteNormalizedCache.swift, AWSAppSyncUnitTests/MutationOptimisticUpdateTests.swift
#92 (kinda?)
As part of working around an issue allowing optimistic updates of query results that haven't been retrieved from the service, @palpatim introduced code to pre-populate an empty table with an empty QUERY_ROOT, resolving the issue. However the issue resurfaces if at any point the caches are cleared, as the table is not then repopulated with the empty QUERY_ROOT.
So if, for example, a user installs an app for the first time and log into an account backed by AWS App Sync, the existing workaround correctly ensures that optimistic updates don't fail when the underlying query results have not been fetched from the service, but if that user were to sign out (causing the caches to be cleared) and then into another account, the …
=> fix: Repopulate records table with empty QUERY_ROOT after caches are cleared

README.md
=> Add guidance with links to use Amplify over AppSync SDK

AWSAppSync.podspec, Package.resolved, Package.swift, Podfile, Podfile.lock
- update AppSyncRealTimeClient dependency version before bumping to 3.2.0
=> fix: update AppSyncRTC dependency version

AWSAppSyncClient/Internal/SubscriptionFactory/APIKeyBasedConnectionPool.swift, AWSAppSyncIntegrationTests/SubscriptionTests.swift, AWSAppSyncUnitTests/Logging/AppSyncLogHelperTests.swift, CHANGELOG.md, Podfile.lock
**Issue #, if available:**
- https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/595
**Description of changes:**
This PR fixes crashes happening in `APIKeyBasedConnectionPool` by adding a queue to sync access to the `endPointToProvider` dictionary.
A previous fix was applied to `IAMBasedConnectionPool` here: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/569
Additionally, I'm fixing some tests no longer compiling after upgrading to the latest SDK version.
--- 
=> fix: Making `APIKeyBasedConnectionPool` thread safe

AWSAppSyncClient/Internal/AWSAppSyncSubscriptionMetadataCache.swift, AWSAppSyncClient/Internal/AWSMutationCache.swift, AWSAppSyncClient/Internal/AWSSQLiteNormalizedCache.swift
*Issue #, if available:* [600](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/600)
iOS 18 adds a new Expression type to Foundation which conflicts with SQLite. Explicitly import SQLite's.
=> Fixes #600. Be explicit about which Expression is being imported
